#!/usr/bin/env bash

# Usage: ./start [nongrok|nogrok]

quit() {
    # echo "start EOF"
    kill $ngrok_pid 2> /dev/null
    kill $frpc_pid 2> /dev/null
    exit 0
}
trap quit EXIT

usage() {
    echo "Usage: $(basename $0) [-d] [-f <0|1>] [-n <0|1>]"
    echo "       -h ... Show this help"
    echo "       -d ... Dev Mode"
    echo "       -c ... Console (Run in second terminal to see output from Dev Mode"
    echo "       -f ... Start frpc (Default 1 except when using -d)"
    echo "       -n ... Start ngrok (Default 0)"
    exit 1
}

dev=false
start_frpc=true
start_ngrok=false

# A letter followed by a colon means the switch takes an argument
while getopts "hcdf:n:" opts; do
    case "${opts}" in
        h)
            usage
            exit 1
            ;;
        c)
            textual console -x event -x debug
            exit 0
            ;;
        d)
            dev=true
            start_frpc=false
            start_ngrok=false
            ;;
        f)
            f=${OPTARG}
            [[ $f -eq 0 || $f -eq 1 ]] || usage
            [[ $f -eq 1 || -z $f ]] && start_frpc=true || start_frpc=false
            ;;
        n)
            n=${OPTARG}
            [[ $n -eq 0 || $n -eq 1 ]] || usage
            [[ $n -eq 1 || -z $n ]] && start_ngrok=true || start_ngrok=false
            ;;
        *)
            usage
            exit 1
            ;;
    esac
done

# remove switches from $@
shift $((OPTIND-1))

if $start_frpc; then
    # start frpc (in the background)
    echo "Starting frpc.sh..."
    ./frpc.sh > /dev/null &
    frpc_pid=$!
fi

if $start_ngrok; then
    # start ngrok (in the background)
    echo "Starting ngrok.sh..."
    ./ngrok.sh noui > /dev/null &
    ngrok_pid=$!
fi

# run plotter-server
if $dev; then
    textual run --dev main.py
else
    python main.py
fi
